image: google/nodejs
script:
  - sudo apt-get install git nodejs npm imagemagick build-essential
  - sudo ln -s /usr/bin/nodejs /usr/bin/node
  - sudo add-apt-repository ppa:chris-lea/redis-server
  - sudo apt-get update && sudo apt-get dist-upgrade
  - npm install -g express
  - mkdir var
  - cd var
  - mkdir www
  - cd www
  - git clone http://gitlab.mysimpleclouds.com/james/nodebb2.0 nodebb
  - cd nodebb
  - npm install -g supervisor
  - npm install -g grunt-cli
  - grunt
services:
  - postgres
  - mysql
  - memcached
  - redis-server
  - mongodb
  - npm
notify:
  email:
    recipients:
      - james@jurisdesk.com
  webhook:
    urls:
      - https://webhooks.gitter.im/e/738cec25e34bafb2650f
    on_started: false
    on_success: true
    on_failure: true
