build:
  image: docker/nodejs:0.10
git:
  path: github.com/Jdesk/drone-images
env:
  - GOROOT=/usr/local/go
  - PATH=$PATH:$GOROOT/bin:$GOPATH/bin
script:
  - sudo apt-get -y install git zip libsqlite3-dev sqlite3 dpkg 1> /dev/null 2> /dev/null
  - sudo apt-get install git nodejs nodejs-legacy npm imagemagick build-essential
  - sudo add-apt-repository ppa:chris-lea/redis-server
  - sudo apt-get update && sudo apt-get dist-upgrade
  - make deps
  - make test
  - make test_postgres
  - make test_mysql
  - make packages
  - npm install -g express
  - npm install nodebb
services:
  - postgres
  - mysql
  - memcached
  - redis
  - mongodb
notify:
  email:
    recipients:
      - james@jurisdesk.com
  webhook:
    urls:
      - https://webhooks.gitter.im/e/738cec25e34bafb2650f
    on_started: false
    on_success: true
    on_failure: true

script:
  - sudo apt-get -y install git zip libsqlite3-dev sqlite3 dpkg 1> /dev/null 2> /dev/null
  - sudo apt-get install git nodejs nodejs-legacy npm imagemagick build-essential
  - sudo add-apt-repository ppa:chris-lea/redis-server
  - sudo apt-get update && sudo apt-get dist-upgrade
script:
  - sudo apt-get install git nodejs npm imagemagick build-essential
  - sudo ln -s /usr/bin/nodejs /usr/bin/node
  - sudo add-apt-repository ppa:chris-lea/redis-server
  - sudo apt-get update && sudo apt-get dist-upgrade
  - npm install -g express
  - mkdir var
  - cd var
  - mkdir www
  - cd www
  - git clone http://gitlab.mysimpleclouds.com/james/nodebb2.0 nodebb
  - cd nodebb
  - npm install -g supervisor
  - npm install -g grunt-cli
  - grunt
services:
  - elasticsearch
  - mysql
  - memcached
  - redis
  - mongodb
notify:
  email:
    recipients:
      - james@jurisdesk.com
  webhook:
    urls:
      - https://webhooks.gitter.im/e/738cec25e34bafb2650f
    on_started: false
    on_success: true
    on_failure: true
