image: node
script:
  - sudo apt-get -y install git zip libsqlite3-dev sqlite3 dpkg 1> /dev/null 2> /dev/null
  - sudo apt-get install git nodejs nodejs-legacy npm imagemagick build-essential
  - sudo add-apt-repository ppa:chris-lea/redis-server
  - sudo apt-get update && sudo apt-get dist-upgrade
  - make deps
  - make test
  - make test_postgres
  - make test_mysql
  - make packages
  - npm install -g express
  - npm install nodebb
services:
  - postgres
  - mysql
  - memcached
  - redis
  - mongodb
notify:
  email:
    recipients:
      - james@jurisdesk.com
  webhook:
    urls:
      - https://webhooks.gitter.im/e/738cec25e34bafb2650f
    on_started: false
    on_success: true
    on_failure: true
