build:
  image: bugagazavr/golang
  environment:
    - GOPATH=/drone
  commands:
    - apt-get update 1> /dev/null 2> /dev/null
    - apt-get -y install libsqlite3-dev sqlite3 1> /dev/null 2> /dev/null
    - go get golang.org/x/tools/cmd/vet
    - go get golang.org/x/tools/cmd/cover
  - GOROOT=/usr/local/go
  - PATH=$PATH:$GOROOT/bin:$GOPATH/bin
env:
  - GOPATH=/var/cache/drone
script:
  - sudo apt-get install git nodejs npm imagemagick build-essential
  - sudo ln -s /usr/bin/nodejs /usr/bin/node
  - sudo add-apt-repository ppa:chris-lea/redis-server
  - sudo apt-get update && sudo apt-get dist-upgrade
  - npm install -g express
  - mkdir var
  - cd var
  - mkdir www
  - cd www
  - git clone http://gitlab.mysimpleclouds.com/james/nodebb2.0 nodebb
  - cd nodebb
  - npm install -g supervisor
  - npm install -g grunt-cli
  - grunt
services:
  - elasticsearch
  - mysql
  - memcached
  - redis
  - mongodb
notify:
  email:
    recipients:
      - james@jurisdesk.com
  webhook:
    urls:
      - https://webhooks.gitter.im/e/738cec25e34bafb2650f
    on_started: false
    on_success: true
    on_failure: true
